version: "3"

services:
  prometheus:
    build: .
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
    - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    cap_add:
      - SYS_TIME
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'